/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package is3calendar;

import calendar_ex.*;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;


/**
 *
 * @author Arthur Bigeard
 */
public class IS3Calendar extends javax.swing.JFrame {
    private static CalendarEx cal;
    private static String fileName;
    private static String displayMode;
        
    private static CalendarDate startDate;
    private static CalendarDate endDate; 
    private static GregorianCalendar currentMonthDate;
    /**
     * Creates new form Calendar
     */
    public IS3Calendar() {
        cal = new CalendarEx();
        fileName = "events6.ser";
        displayMode = "Day";

        cal.openCalendar(fileName);
        initComponents();

        monthDisplayPane.setSelectedIndex(0);
        //cal.printCalendar();
        GregorianCalendar today = new GregorianCalendar();
        currentMonthDate = today;
        populateMonth(today);
        populateWeek(today);
        populateDay(new Date());
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAppointmentFrame = new javax.swing.JFrame();
        addAppointmentFrameLocationTextInput = new javax.swing.JTextField();
        addAppointmentFrameCategoryTextInput = new javax.swing.JTextField();
        addAppointmentFrameDateTextInput = new javax.swing.JTextField();
        addAppointmentFrameStartTimeTextInput = new javax.swing.JTextField();
        addAppointmentFrameEndTimeTextInput = new javax.swing.JTextField();
        addAppointmentFrameConfirmButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addAppointmentFrameDescriptionTextarea = new javax.swing.JTextArea();
        addAppointmentFrameRecurrenceComboList = new javax.swing.JComboBox();
        addAppointmentFrameNameTextInput = new javax.swing.JTextField();
        commandLineSubmit = new javax.swing.JButton();
        commandLineInput = new javax.swing.JTextField();
        addAppointmentButton = new javax.swing.JButton();
        monthDisplayPane = new javax.swing.JTabbedPane();
        dayDisplayPane = new javax.swing.JScrollPane();
        dayDisplayTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        weekDisplayTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        monthDisplayTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        addAppointmentFrame.setMinimumSize(new java.awt.Dimension(500, 500));

        addAppointmentFrameLocationTextInput.setText("Location");
        addAppointmentFrameLocationTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameLocationTextInputMouseClicked(evt);
            }
        });
        addAppointmentFrameLocationTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentFrameLocationTextInputActionPerformed(evt);
            }
        });

        addAppointmentFrameCategoryTextInput.setText("Category");
        addAppointmentFrameCategoryTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameCategoryTextInputMouseClicked(evt);
            }
        });
        addAppointmentFrameCategoryTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentFrameCategoryTextInputActionPerformed(evt);
            }
        });

        addAppointmentFrameDateTextInput.setText("Date (DD/MM/YYYY)");
        addAppointmentFrameDateTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameDateTextInputMouseClicked(evt);
            }
        });

        addAppointmentFrameStartTimeTextInput.setText("Start time (hh:mm)");
        addAppointmentFrameStartTimeTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameStartTimeTextInputMouseClicked(evt);
            }
        });

        addAppointmentFrameEndTimeTextInput.setText("End time (hh:mm)");
        addAppointmentFrameEndTimeTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameEndTimeTextInputMouseClicked(evt);
            }
        });

        addAppointmentFrameConfirmButton.setText("Confirm");
        addAppointmentFrameConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentFrameConfirmButtonActionPerformed(evt);
            }
        });

        addAppointmentFrameDescriptionTextarea.setColumns(20);
        addAppointmentFrameDescriptionTextarea.setRows(5);
        addAppointmentFrameDescriptionTextarea.setText("Description");
        addAppointmentFrameDescriptionTextarea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameDescriptionTextareaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addAppointmentFrameDescriptionTextarea);

        addAppointmentFrameRecurrenceComboList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Daily", "Weekly", "Two weekly", "Four weekly" }));

        addAppointmentFrameNameTextInput.setText("Name");
        addAppointmentFrameNameTextInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAppointmentFrameNameTextInputMouseClicked(evt);
            }
        });
        addAppointmentFrameNameTextInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentFrameNameTextInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addAppointmentFrameLayout = new javax.swing.GroupLayout(addAppointmentFrame.getContentPane());
        addAppointmentFrame.getContentPane().setLayout(addAppointmentFrameLayout);
        addAppointmentFrameLayout.setHorizontalGroup(
            addAppointmentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addAppointmentFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addAppointmentFrameConfirmButton)
                .addGap(41, 41, 41))
            .addGroup(addAppointmentFrameLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(addAppointmentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addAppointmentFrameRecurrenceComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addAppointmentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addAppointmentFrameLocationTextInput)
                        .addComponent(addAppointmentFrameCategoryTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(addAppointmentFrameNameTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addComponent(addAppointmentFrameEndTimeTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAppointmentFrameStartTimeTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAppointmentFrameDateTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addAppointmentFrameLayout.setVerticalGroup(
            addAppointmentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAppointmentFrameLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(addAppointmentFrameNameTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAppointmentFrameLocationTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAppointmentFrameCategoryTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addAppointmentFrameDateTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAppointmentFrameStartTimeTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAppointmentFrameEndTimeTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAppointmentFrameRecurrenceComboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(addAppointmentFrameConfirmButton)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        commandLineSubmit.setText("Submit");
        commandLineSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandLineSubmitActionPerformed(evt);
            }
        });

        commandLineInput.setText("/");
        commandLineInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commandLineInputActionPerformed(evt);
            }
        });

        addAppointmentButton.setText("Add");
        addAppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppointmentButtonActionPerformed(evt);
            }
        });

        monthDisplayPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                monthDisplayPaneStateChanged(evt);
            }
        });
        monthDisplayPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthDisplayPaneFocusGained(evt);
            }
        });

        dayDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00", null},
                {"9:00", null},
                {"10:00", null},
                {"11:00", null},
                {"12:00", null},
                {"13:00", null},
                {"14:00", null},
                {"15:00", null},
                {"16:00", null},
                {"17:00", null},
                {"18:00", null},
                {"19:00", null},
                {"20:00", null},
                {"21:00", null},
                {"22:00", null},
                {"23:00", null},
                {"00:00", null},
                {"1:00", null},
                {"2:00", null},
                {"3:00", null},
                {"4:00", null},
                {"5:00", null},
                {"6:00", null},
                {"7:00", null}
            },
            new String [] {
                "Time", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dayDisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dayDisplayTableMouseClicked(evt);
            }
        });
        dayDisplayPane.setViewportView(dayDisplayTable);
        dayDisplayTable.getColumnModel().getColumn(0).setMinWidth(60);
        dayDisplayTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        dayDisplayTable.getColumnModel().getColumn(0).setMaxWidth(60);

        monthDisplayPane.addTab("Day", dayDisplayPane);

        weekDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"8:00", null, null, null, null, null, null, null},
                {"9:00", null, null, null, null, null, null, null},
                {"10:00", null, null, null, null, null, null, null},
                {"11:00", null, null, null, null, null, null, null},
                {"12:00", null, null, null, null, null, null, null},
                {"13:00", null, null, null, null, null, null, null},
                {"14:00", null, null, null, null, null, null, null},
                {"15:00", null, null, null, null, null, null, null},
                {"16:00", null, null, null, null, null, null, null},
                {"17:00", null, null, null, null, null, null, null},
                {"18:00", null, null, null, null, null, null, null},
                {"19:00", null, null, null, null, null, null, null},
                {"20:00", null, null, null, null, null, null, null},
                {"21:00", null, null, null, null, null, null, null},
                {"22:00", null, null, null, null, null, null, null},
                {"23:00", null, null, null, null, null, null, null},
                {"00:00", null, null, null, null, null, null, null},
                {"1:00", null, null, null, null, null, null, null},
                {"2:00", null, null, null, null, null, null, null},
                {"3:00", null, null, null, null, null, null, null},
                {"4:00", null, null, null, null, null, null, null},
                {"5:00", null, null, null, null, null, null, null},
                {"6:00", null, null, null, null, null, null, null},
                {"7:00", null, null, null, null, null, null, null}
            },
            new String [] {
                "Time", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(weekDisplayTable);
        weekDisplayTable.getColumnModel().getColumn(0).setMinWidth(60);
        weekDisplayTable.getColumnModel().getColumn(0).setMaxWidth(60);

        monthDisplayPane.addTab("Week", jScrollPane3);

        monthDisplayTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        monthDisplayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        monthDisplayTable.setRowHeight(40);
        monthDisplayTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                monthDisplayTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(monthDisplayTable);
        monthDisplayTable.getColumnModel().getColumn(0).setHeaderValue("Monday");
        monthDisplayTable.getColumnModel().getColumn(1).setHeaderValue("Tuesday");
        monthDisplayTable.getColumnModel().getColumn(2).setHeaderValue("Wednesday");
        monthDisplayTable.getColumnModel().getColumn(3).setHeaderValue("Thursday");
        monthDisplayTable.getColumnModel().getColumn(4).setHeaderValue("Friday");
        monthDisplayTable.getColumnModel().getColumn(5).setHeaderValue("Saturday");
        monthDisplayTable.getColumnModel().getColumn(6).setHeaderValue("Sunday");

        monthDisplayPane.addTab("Month", jScrollPane4);

        jButton1.setText("Prev");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(commandLineInput, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commandLineSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addAppointmentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(monthDisplayPane, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandLineSubmit)
                    .addComponent(commandLineInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAppointmentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(monthDisplayPane, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentButtonActionPerformed
        addAppointmentFrame.setTitle("New appointment");
        addAppointmentFrame.setVisible(true);
    }//GEN-LAST:event_addAppointmentButtonActionPerformed

    private void addAppointmentFrameLocationTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentFrameLocationTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAppointmentFrameLocationTextInputActionPerformed

    private void commandLineInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandLineInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_commandLineInputActionPerformed

    private void addAppointmentFrameConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentFrameConfirmButtonActionPerformed

        boolean validInput = true;
        String location = addAppointmentFrameLocationTextInput.getText();
        String name = addAppointmentFrameNameTextInput.getText();
        String description = addAppointmentFrameDescriptionTextarea.getText();
        String category = addAppointmentFrameCategoryTextInput.getText();
        String date = addAppointmentFrameDateTextInput.getText();
        String start = addAppointmentFrameStartTimeTextInput.getText();
        String end = addAppointmentFrameEndTimeTextInput.getText();
        Appointment.Recurrence rec = Appointment.Recurrence.valueOf(((String) addAppointmentFrameRecurrenceComboList.getModel().getElementAt(addAppointmentFrameRecurrenceComboList.getSelectedIndex())).toUpperCase());
        System.out.println(rec);
        int remind = 0;
        
        String[] arrDate = date.split("/");
        String[] arrStartTime = start.split(":");
        String[] arrEndTime = end.split(":");
        
        CalendarDate cDate = new CalendarDate(Integer.parseInt(arrDate[0]), Integer.parseInt(arrDate[1]), Integer.parseInt(arrDate[2]));
        CalendarTime cStart = new CalendarTime(Integer.parseInt(arrStartTime[0]), Integer.parseInt(arrStartTime[1]));
        CalendarTime cEnd = new CalendarTime(Integer.parseInt(arrEndTime[0]), Integer.parseInt(arrEndTime[1]));
       
        Appointment ap = new Appointment(cDate, cStart, cEnd, name.trim(), description.trim(), location, category, rec, remind);
        /*   validInput = CalendarDate.isValidDateString(date);
        validInput = CalendarTime.isValidTimeString(start);
        validInput = CalendarTime.isValidTimeString(end);*/
        if(validInput){
            cal.addAppointment(ap);
            cal.saveCalendar(fileName);
            addAppointmentFrame.setVisible(false); 
            if(displayMode == "Month"){
                populateMonth(currentMonthDate);
            }
            else if(displayMode == "Week"){
               populateWeek(currentMonthDate);
            }
            else{
                populateDay(new Date());
            }
        }
        else{
            
        }
        
        
         /*example: assume range of dates is between 1st and 30th of November, 2012 in Month tab.
        *need some if statements here to check which tab we're on. Weekly range for week etc
        *
        * 
        * each appointment object should have some click state so it can be edited, removed etc
        * 
        * 
        * a reoccuring appointment will be displayed if it falls within the dates, it should be 
        * colour coded identically, to represent a duplicate of that appointment
        * 
        * 
        * this code should be contained within a function, as a removal will also need to redisplay
        * the calendar view
        * 
        */
        
        //these dates will change dependant on the tab state
        startDate = new CalendarDate(1,11,2012);
        endDate = new CalendarDate(30,11,2012);
        
        
        //get list of appointments between start and end dates
        List<Appointment> a = cal.getAppointmentsBetweenDates(startDate, endDate);
       
        System.out.println("Relevant appointments between " + startDate + " and " + endDate + " :");
        int i =0;
        for(Appointment app : a){
            System.out.print("Appointment number: "  + i + " "+ app);
              //some code to create an appointment box for this in the table
            
            //also get recurrence dates for date range, these need to be displayed 
              List<CalendarDate> recurs = app.getRecurrenceDates(startDate, endDate);
              
              for(CalendarDate d : recurs){
                  System.out.println("This appointment will also be displayed (as a duplicate) on " + d);
                  //some code to create an identical appointment box for this recurrence in the table
              }
            i++;
        }
        

        
        
    }//GEN-LAST:event_addAppointmentFrameConfirmButtonActionPerformed
    
    private void populateMonth(GregorianCalendar today) {
        int[] dayOffset = {6,0,1,2,3,4,5};
        for (int x = 0; x < monthDisplayTable.getRowCount(); x++) {
            for (int y = 0; y < monthDisplayTable.getColumnCount(); y++) {
                 monthDisplayTable.setValueAt(null, x, y);
            }
        }
        HashMap<Integer,ArrayList<String>> recdates = new HashMap<Integer,ArrayList<String>>();
        int dayFix = dayOffset[today.get(Calendar.DAY_OF_WEEK)-1];
        int monthDays = today.getActualMaximum(Calendar.DAY_OF_MONTH);
        today.set(Calendar.DAY_OF_MONTH, 1);
        int startDay = dayOffset[today.get(Calendar.DAY_OF_WEEK)-1];
        int i = 0;
        
        startDate = new CalendarDate(today.get(Calendar.DAY_OF_MONTH)
                ,today.get(Calendar.MONTH)+1,today.get(Calendar.YEAR));
        endDate = new CalendarDate(monthDays,today.get(Calendar.MONTH)+1,
                today.get(Calendar.YEAR));
        
        //get list of appointments between start and end dates
        System.out.println(startDate + " " + endDate);
        List<Appointment> apps = cal.getAppointmentsBetweenDates(startDate, endDate);
        for (int x = 0; x < monthDisplayTable.getRowCount(); x++) {
            for (int y = startDay; y < monthDisplayTable.getColumnCount(); y++) {
                if (i >= monthDays) { break; }
                i++;
                String s = i+" - ";
                if (recdates.containsKey(i)) {
                    List<String> temwtf = recdates.get(i);
                    //System.out.println(temwtf);
                    for (String gn : temwtf) {
                        s = s + gn + " / ";
                    }
                }
                for (Appointment a : apps) {
                    if (a.date.day == i) {
                        s = s + a.name + " / ";
                        List<CalendarDate> recurs = a.getRecurrenceDates(startDate, endDate);
                        ArrayList<String> tempn = new ArrayList<String>();
                        for(CalendarDate d : recurs){
                            if (recdates.containsKey(d.day)) {
                                ArrayList<String> humm = recdates.get(d.day);
                                for (String s2 : humm) {
                                    if (!tempn.contains(s2)) {
                                        tempn.add(s2);
                                    }
                                }
                            }
                            if (!tempn.contains(a.name)) {
                                tempn.add(a.name);
                            }
                            //System.out.println(d.day + " " + tempn);
                            recdates.put(d.day,tempn);
                            //tempn.clear();
                        }
                        //System.out.println(recdates);
                        
                    }
                    
                    //monthDisplayTable.setValueAt(s2, x, y);
                }
                s = s.substring(0, s.length()-3);
                monthDisplayTable.setValueAt(s, x, y);
            }
            startDay = 0;
        }
        jLabel1.setText(new SimpleDateFormat("MMMM yyyy").format(today.getTime()));
 }
    
    private void populateWeek(GregorianCalendar today) {
        int dates[] = new int[7];
        DateFormat dateFormat = new SimpleDateFormat("dd");
        Calendar c = Calendar.getInstance();
        int day = Integer.parseInt(dateFormat.format(c.getTime()));
        
        jLabel1.setText(new SimpleDateFormat("MMMM yyyy").format(today.getTime()) + " - Week "+(Math.round(day / 7)+1));
 }
    
    private void populateDay(Date today) {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String strDate = dateFormat.format(today.getTime());
        String[] arrDate = strDate.split("/");
        CalendarDate begin = new CalendarDate(Integer.parseInt(arrDate[0]), Integer.parseInt(arrDate[1]), Integer.parseInt(arrDate[2]));
        ArrayList<Appointment> list = new ArrayList<>();
        list = (ArrayList) cal.getAppointmentsBetweenDates(begin, begin);
        for(Appointment ap : list){
            int hour = ap.start_time.hr-8;
            if(hour < 0){
                hour = 24 + hour;
            }
            dayDisplayTable.setValueAt(ap, hour, 1);
        }
        jLabel1.setText(strDate);
 }
    private void commandLineSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commandLineSubmitActionPerformed

    }//GEN-LAST:event_commandLineSubmitActionPerformed

    private void monthDisplayPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_monthDisplayPaneStateChanged
         int i = monthDisplayPane.getSelectedIndex();
         if(i == 0){
             displayMode = "Day";
             populateDay(new Date());
         }
         else if(i == 1){
             displayMode = "Week";
             populateWeek(new GregorianCalendar());
         }
         else{
             displayMode = "Month";
             populateMonth(new GregorianCalendar());
         }
    }//GEN-LAST:event_monthDisplayPaneStateChanged

    private void monthDisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monthDisplayTableMouseClicked
        int row = monthDisplayTable.rowAtPoint(evt.getPoint());
        int col = monthDisplayTable.columnAtPoint(evt.getPoint());        // TODO add your handling code here:
        System.out.println(row + " " + col);
    }//GEN-LAST:event_monthDisplayTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                GregorianCalendar nextMonth = new GregorianCalendar();
                nextMonth.set(Calendar.MONTH, currentMonthDate.get(Calendar.MONTH)-1);
                nextMonth.set(Calendar.DAY_OF_MONTH, 1);
                currentMonthDate = nextMonth;
                populateMonth(nextMonth);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

                GregorianCalendar nextMonth = new GregorianCalendar();
                nextMonth.set(Calendar.MONTH, currentMonthDate.get(Calendar.MONTH)+1);
                nextMonth.set(Calendar.DAY_OF_MONTH, 1);
                currentMonthDate = nextMonth;
                populateMonth(nextMonth);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dayDisplayTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dayDisplayTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dayDisplayTableMouseClicked

    private void addAppointmentFrameNameTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentFrameNameTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAppointmentFrameNameTextInputActionPerformed

    private void monthDisplayPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthDisplayPaneFocusGained

    }//GEN-LAST:event_monthDisplayPaneFocusGained

    private void addAppointmentFrameNameTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameNameTextInputMouseClicked
        if (addAppointmentFrameNameTextInput.getText().compareTo("Name") == 0) {
            addAppointmentFrameNameTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameNameTextInputMouseClicked

    private void addAppointmentFrameLocationTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameLocationTextInputMouseClicked
        if (addAppointmentFrameLocationTextInput.getText().compareTo("Location") == 0) {
            addAppointmentFrameLocationTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameLocationTextInputMouseClicked

    private void addAppointmentFrameCategoryTextInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppointmentFrameCategoryTextInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAppointmentFrameCategoryTextInputActionPerformed

    private void addAppointmentFrameCategoryTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameCategoryTextInputMouseClicked
        if (addAppointmentFrameCategoryTextInput.getText().compareTo("Category") == 0) {
            addAppointmentFrameCategoryTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameCategoryTextInputMouseClicked

    private void addAppointmentFrameDescriptionTextareaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameDescriptionTextareaMouseClicked
        if (addAppointmentFrameDescriptionTextarea.getText().compareTo("Description") == 0) {
            addAppointmentFrameDescriptionTextarea.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameDescriptionTextareaMouseClicked

    private void addAppointmentFrameDateTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameDateTextInputMouseClicked
        if (addAppointmentFrameDateTextInput.getText().compareTo("Date (DD/MM/YYYY)") == 0) {
            addAppointmentFrameDateTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameDateTextInputMouseClicked

    private void addAppointmentFrameStartTimeTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameStartTimeTextInputMouseClicked
        if (addAppointmentFrameStartTimeTextInput.getText().compareTo("Start time (hh:mm)") == 0) {
            addAppointmentFrameStartTimeTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameStartTimeTextInputMouseClicked

    private void addAppointmentFrameEndTimeTextInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAppointmentFrameEndTimeTextInputMouseClicked
        if (addAppointmentFrameEndTimeTextInput.getText().compareTo("End time (hh:mm)") == 0) {
            addAppointmentFrameEndTimeTextInput.setText("");
        }
    }//GEN-LAST:event_addAppointmentFrameEndTimeTextInputMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           @Override
            public void run() {
                IS3Calendar c = new IS3Calendar();
                c.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppointmentButton;
    private javax.swing.JFrame addAppointmentFrame;
    private javax.swing.JTextField addAppointmentFrameCategoryTextInput;
    private javax.swing.JButton addAppointmentFrameConfirmButton;
    private javax.swing.JTextField addAppointmentFrameDateTextInput;
    private javax.swing.JTextArea addAppointmentFrameDescriptionTextarea;
    private javax.swing.JTextField addAppointmentFrameEndTimeTextInput;
    private javax.swing.JTextField addAppointmentFrameLocationTextInput;
    private javax.swing.JTextField addAppointmentFrameNameTextInput;
    private javax.swing.JComboBox addAppointmentFrameRecurrenceComboList;
    private javax.swing.JTextField addAppointmentFrameStartTimeTextInput;
    private javax.swing.JTextField commandLineInput;
    private javax.swing.JButton commandLineSubmit;
    private javax.swing.JScrollPane dayDisplayPane;
    private javax.swing.JTable dayDisplayTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane monthDisplayPane;
    private javax.swing.JTable monthDisplayTable;
    private javax.swing.JTable weekDisplayTable;
    // End of variables declaration//GEN-END:variables
}
